// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxgVG2Z0CQKBWDMjmlQDtGHN9GdG9-tk',
    appId: '1:404344995033:web:8a8a4e0fc212f67dbd92c8',
    messagingSenderId: '404344995033',
    projectId: 'pedefacilentregadores-f5b14',
    authDomain: 'pedefacilentregadores-f5b14.firebaseapp.com',
    storageBucket: 'pedefacilentregadores-f5b14.appspot.com',
    measurementId: 'G-4YGDCSBPQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8W40DRtOfD1eTwxIOWmUkrwMb7200b18',
    appId: '1:404344995033:android:6b44d4c1a1010076bd92c8',
    messagingSenderId: '404344995033',
    projectId: 'pedefacilentregadores-f5b14',
    storageBucket: 'pedefacilentregadores-f5b14.appspot.com',
  );
}
